[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
solady = "0.0.250"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
